server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/local-service-market-place

cors:
  allowed-origins: http://localhost:4200